//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento90mil
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ALMACEN
    {
        [Required]
        [Display(Name = "ID empleado")]
        public int ID_ALMACEN { get; set; }

        [Required]
        [MaxLength(60)]
        [Display(Name = "Descripcion")]
        public string DESCRIPCION { get; set; }

        [Required]
        [Display(Name = "Estado")]
        public string ESTADO { get; set; }
    }
}
