//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento90mil
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.TRANSACCIONs = new HashSet<TRANSACCION>();
        }

        [Display(Name = "Id articulo")]
        [Required]
        public int ID_ARTICULO { get; set; }

        [Display(Name = "Descripcion articulo")]
        public string DESCRIPCION_ARTICULO { get; set; }

        [Display(Name = "Existencia articulo")]
        [Required]
        public bool EXISTENCIA_ARTICULO { get; set; }

        [Display(Name = "ID inventario")]
        [Required]
        public string ID_TIPOINVENTARIO { get; set; }

        [Display(Name = "Costo unitario")]
        public int COSTOUNITARIO { get; set; }

        [Display(Name = "Estado")]
        [Required]
        public string ESTADO { get; set; }


    
        public virtual TIPOINVENTARIO TIPOINVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCIONs { get; set; }
    }
}
