//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento90mil
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TIPOINVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPOINVENTARIO()
        {
            this.ARTICULOes = new HashSet<ARTICULO>();
        }

        [Required]
        [Display(Name = "ID Tipo inventario")]
        public string ID_TIPOINVENTARIO { get; set; }

        [Required]
        [Display(Name = "Descripcion inventario")]
        public string DESCRIPCION_INVENTARIO { get; set; }

        [Required]
        [Display(Name = "Cuenta contable")]
        public Nullable<bool> CUENTACONTABLE { get; set; }

        [Required]
        [Display(Name = "Estado")]
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULOes { get; set; }
    }
}
