//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento90mil
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TRANSACCION
    {
        [Required]
        [Display(Name = "ID transaccion")]
        public int ID_TRANSACCION { get; set; }

        [Required]
        [Display(Name = "Tipo transaccion")]
        public string TIPO_TRANSACCION { get; set; }

        [Required]
        [Display(Name = "ID articulo")]
        public Nullable<int> ID_ARTICULO { get; set; }

        [Required]
        [Display(Name = "Fecha transaccion")]
        public Nullable<System.DateTime> FECHA_TRANSACCION { get; set; }

        [Required]
        [Display(Name = "Cantidad transaccion")]
        public Nullable<bool> CANTIDAD_TRANSACCION { get; set; }

        [Required]
        [Display(Name = "Monto transaccion")]
        public Nullable<int> MONTO_TRANSACCION { get; set; }

        [Required]
        [Display(Name = "Articulo")]
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
